In [3]:
import numpy as np

import sys
sys.path.append('..')

from ml_scratch.neuron import Neuron
from ml_scratch.functions.binary_functions import sigmoid

from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

# Neurônio

Para este exemplo, será utilizada a função **sigmóide** como função de ativação

$$y = \frac{1}{1 + e^{-x}}$$

## Obtendo a saída de um neurônio

Soma ponderada entre a entrada e os pesos
$$z = \sum_{i=1}^n w_ix_i + b$$

Ou simplesmente

$$z = \textbf{w}^T \textbf{x} + b$$

Onde
- $\textbf{w}$ é o vetor de pesos;
- $\textbf{x}$ é o vetor de entrada;
- $b$ é o viés;

Valor de saída do neurônio
$$y = \frac{1}{1 + e^{-z}}$$
$$y = \frac{1}{1 + e^{-(\sum_{i=1}^n w_ix_i + b)}}$$

## Exemplo prático

In [4]:
weights = [1, 1]
inputs = [1, 3]
bias = -1

neuron = Neuron(
    weights=weights,
    bias=bias,
    activation=sigmoid
)

output = neuron.forward(inputs=inputs)
output

0.9525741268224334

No exemplo acima, temos o vetor de entrada $\textbf{x}$, o vetor de pesos $\textbf{w}$ e o bias $b$

$$\textbf{x} = \begin{pmatrix}1, 3\end{pmatrix}$$
$$\textbf{w} = \begin{pmatrix}1, 1\end{pmatrix}$$
$$b = -1$$

Encontrando o valor $z$ da soma ponderada

$$z = (1 \cdot 1) + (3 \cdot 1) + b$$
$$z = 1 + 3 - 1$$
$$z = 3$$

Obtendo o valor de saída aplicando $z$ na função sigmóide

$$y = \frac{1}{1 + e^{(-3)}}$$
$$y \approx 0.9525$$

In [5]:
sigmoid(3)

0.9525741268224334

## Utilizando a implementação do `tensorflow`

In [6]:
model = Sequential()
model.add(Dense(units=1, activation='sigmoid', input_shape=(2,)))

In [7]:
# inputs
inputs = np.array(inputs).reshape(1,2)
inputs

array([[1, 3]])

In [8]:
# weights
weights = np.array(weights).reshape(2,1)
weights

array([[1],
       [1]])

In [9]:
# bias
bias = np.array([bias])
bias

array([-1])

In [10]:
model.set_weights([weights, bias])

output = model.predict(inputs)
output

1/1 [==============================] - 0s 94ms/step


array([[0.95257413]], dtype=float32)